import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { AppState, AppThunk } from "../../store";
import { Course } from "../../types/course";

export interface ApiServerTokenState {
  value: number;
  status: "idle" | "loading" | "error" | "completed";
  apiServerToken: string | undefined;
}

const initialState: ApiServerTokenState = {
  value: 0,
  status: "idle",
  apiServerToken: undefined,
};

export const apiServerTokenSlice = createSlice({
  name: "apiServerToken",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    store: (state,action) => {
        state.apiServerToken = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { store } = apiServerTokenSlice.actions

export const selectApiServerToken = (state: AppState) => state.apiServerToken;

export default apiServerTokenSlice.reducer;
